name: template_2025
description: "A new Flutter project template."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  rush:
    git:
      url: https://github.com/khaledSayedAbdellah/rush
      ref: "2ff9fce"
  fast_http: ^1.0.3
  go_router: ^7.1.1
  provider: ^6.0.5

  get_it: ^7.6.0
  shared_preferences: ^2.1.1
  photo_view: ^0.14.0
  flutter_screenutil: ^5.9.3
  state_extended: ^5.5.0
  equatable: ^2.0.5
  internet_connection_checker_plus: ^2.0.0
  dartz: ^0.10.1
  http: ^1.0.0

  intl: any

  google_fonts: ^5.1.0
  pin_code_fields: ^8.0.1
  popover: ^0.3.1
  flutter_svg:  ^2.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svg/
    - i18n/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
